config/routes.rb
Rails.application.routes.draw do
  post 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @quota_development = []
    @amount = params["amount"].to_f
    @term = params["term"].to_i
    @interest = params["interest"].to_f
    @amortization = @amount/@term
    @total = 0
      @term.times do |time|
      if @amount > 0
        line = {}
        line["month"] = (time + 1)
        if time > 0
          if @amount > @amortization
            @amount -= @amortization
          else
            @amount -= @amount
          end
        else
          
        end
        @interests = @amount * (@interest/100)      
        @quota_month = @amortization + @interests
        line["amount"] = @amount  
        line["balance_final"] = @amount         
        line["amortization"] = @amortization
        line["interests"] = @interests
        line["quota_month"] = @quota_month
        @total += @quota_month
      end
      @quota_development.push(line)
    end
    puts @quota_development
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_tag(home_index_path) do %>
  <%= text_field_tag 'amount', '', :placeholder => 'Monto', :value => '6000' %></p>
  <%= text_field_tag 'term', '', :placeholder => 'Número de meses', :value => '6' %></p>
  <%= text_field_tag 'interest', '', :placeholder => 'Interes mensual', :value => '2.5' %></p>
  <div><%= submit_tag 'Calcular' %></div>
<% end %>
<% if @quota_development.length > 0%>
  Pagaras en total <%=@total%>
  <table>
    <thead>
      <% @quota_development.first.keys.each do |key|%>
        <td>
          <%= key %>
        </td>
      <%end%>
    </thead>
    <tbody>
      <% @quota_development.each do |quota|%>
        <tr>
          <% quota.keys.each do |key|%>
            <td>
              <%= quota[key]%>
            </td>
          <%end%>
        </tr>
      <%end%>
    </tbody>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>